### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by EssendonPhoto** [stjohnjohnson/mqtt-dasher#4]

**Comment by stjohnjohnson** [comment]
Please reopen with a description and more details.

**Comment by stjohnjohnson** [comment]
Looks like all your comments disappeared, here's what's in my email:
```
Hi

I am trying to run this on a pi running hassbian (an installation type of Home Assistant), and am getting the following error:
`$ CONFIG_DIR=~ mqtt-dasher
info: Starting MQTT Amazon Dash - v0.1.0
info: Loading configuration

/usr/lib/node_modules/mqtt-dasher/node_modules/js-yaml/lib/js-yaml/loader.js:171
throw generateError(state, message);
^
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 10, column 5:
# Preface for the topics $PREFAC ...
^
at generateError (/usr/lib/node_modules/mqtt-dasher/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
at throwError (/usr/lib/node_modules/mqtt-dasher/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
at readBlockMapping (/usr/lib/node_modules/mqtt-dasher/node_modules/js-yaml/lib/js-yaml/loader.js:1046:9)
at composeNode (/usr/lib/node_modules/mqtt-dasher/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
at readBlockMapping (/usr/lib/node_modules/mqtt-dasher/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
at composeNode (/usr/lib/node_modules/mqtt-dasher/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
at readDocument (/usr/lib/node_modules/mqtt-dasher/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
at loadDocuments (/usr/lib/node_modules/mqtt-dasher/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
at load (/usr/lib/node_modules/mqtt-dasher/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
at Object.safeLoad (/usr/lib/node_modules/mqtt-dasher/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
`

The reason that I have put a config.yml in ~ is that the default one from your instructions (in /opt/mqtt-dasher did not exist)

The installation seemed to work, though threw the following errors:
`$ sudo npm install -g mqtt-dasher
/usr/bin/mqtt-dasher -> /usr/lib/node_modules/mqtt-dasher/bin/mqtt-dasher

socketwatcher@0.3.0 install /usr/lib/node_modules/mqtt-dasher/node_modules/socketwatcher
node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.11.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/mqtt-dasher/node_modules/socketwatcher/.node-gyp"
make: Entering directory '/usr/lib/node_modules/mqtt-dasher/node_modules/socketwatcher/build'
CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::New(const Nan::FunctionCallbackInfov8::Value&)’:
../socket_watcher.cpp:104:49: warning: ‘v8::Localv8::Object v8::Function::NewInstance() const’ is deprecated (declared at /usr/lib/node_modules/mqtt-dasher/node_modules/socketwatcher/.node-gyp/6.11.0/include/node/v8.h:3276): Use maybe version [-Wdeprecated-declarations]
info.GetReturnValue().Set(cons->NewInstance());
^
SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
COPY Release/socketwatcher.node
make: Leaving directory '/usr/lib/node_modules/mqtt-dasher/node_modules/socketwatcher/build'

pcap@2.0.0 install /usr/lib/node_modules/mqtt-dasher/node_modules/pcap
node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.11.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/mqtt-dasher/node_modules/pcap/.node-gyp"
make: Entering directory '/usr/lib/node_modules/mqtt-dasher/node_modules/pcap/build'
CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
CXX(target) Release/obj.target/pcap_binding/pcap_session.o
../pcap_session.cc: In static member function ‘static void PcapSession::New(const Nan::FunctionCallbackInfov8::Value&)’:
../pcap_session.cc:46:49: warning: ‘v8::Localv8::Object v8::Function::NewInstance() const’ is deprecated (declared at /usr/lib/node_modules/mqtt-dasher/node_modules/pcap/.node-gyp/6.11.0/include/node/v8.h:3276): Use maybe version [-Wdeprecated-declarations]
info.GetReturnValue().Set(cons->NewInstance());
^
SOLINK_MODULE(target) Release/obj.target/pcap_binding.node
COPY Release/pcap_binding.node
make: Leaving directory '/usr/lib/node_modules/mqtt-dasher/node_modules/pcap/build'
/usr/lib
└─┬ mqtt-dasher@0.1.0
`

I am running node 6.11

Any suggestions?
```

**Comment by stjohnjohnson** [comment]
Can you share your config file?
